services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../app:/var/task
    depends_on:
      - db
    networks:
      - app
    env_file:
      - dev.env

  db:
    image: docker.io/postgres:16.4-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

volumes:
  db:
    driver: local

networks:
  app:
